try:
    func(2, None)
except ValueError:
    print("Ура! Ошибка!")